### ISSUE TITLE
Add cross-level cache invalidation mechanisms

### ISSUE THREAD

**Issue by vittoriom** [spring-media/Carlos#89]
Ideal requirements:
- It should work with the out-of-the-box levels
- It should be easy to integrate with custom levels
- It should handle expiration timestamps or other means of invalidation
- It should be as unobtrusive as possible

Tasks:
- [ ] Update tests
- [ ] Update code documentation
- [ ] Update sample code
- [ ] Update README.md
- [ ] Update CHANGELOG.md
- [ ] Update MIGRATIONS.md
- [ ] Update Github milestone

**Comment by vittoriom** [comment]
A possible solution is to introduce a `CacheExpirationHandler`, that acts as a `OneWayTransformer` applied through a `postProcess` on an existing `CacheLevel`, that can invalidate the result if an invalidation condition applies.

**Comment by pkcpkc** [comment]
Additionally it would be great to respect the http max-age header, starting from the network fetcher - or other fetchers.
This would result in a big refactoring because you would need to transport the maxAge information through all the layers, starting from the fetcher over all caching layers to the output.

**Comment by ivanlisovyi** [comment]
We aren't yet sure what we're gonna do with Carlos and where do we see it in the future hence to avoid spreading misinformation about the future development of Carlos I'm closing this issue for now. 

Also, we're tracking this issue internally and we will see if we really need this functionality in Carlos.
